/*
* NombreProgra.asm
*
* Creado: 24/02/2026 23:21:52
* Autor : José Alfaro 
* Descripción: Proyecto 1
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
.equ T1_VALOR			= 0x1B1E
.def MODO				= R20		

//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

//COLOCAMOS VECTORES DE INTERRUPCIONES
.cseg
.org 0x0000
	RJMP START
.org PCI1addr
	RJMP PIN_CHANGE_ISR
.org OVF1addr
	RJMP TIMER1_ISR
.org OVF0addr
	RJMP TIMER0_ISR

START:
 /****************************************/
// Configuración de la pila 
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16
/****************************************/
//DESIGNAMOS REGISTROS EN LA RAM
 .dseg
 COPIA_SEGUNDO_MIN: .byte 1
 COPIA_PRIMERO_MIN: .byte 1
 COPIA_SEGUNDO_HORA: .byte 1
 COPIA_PRIMERO_HORA: .byte 1
 COPIA_SEGUNDO_DIA: .byte 1
 COPIA_PRIMERO_DIA: .byte 1
 COPIA_SEGUNDO_MES: .byte 1
 COPIA_PRIMERO_MES: .byte 1
 ALARMA_SEGUNDO_HORA: .byte 1
 ALARMA_PRIMERO_HORA: .byte 1
 ALARMA_SEGUNDO_MIN: .byte 1
 ALARMA_PRIMERO_MIN: .byte 1
 CONTADOR_TIMER0: .byte 1
 .cseg
// Configuracion MCU
SETUP:
	CLI //DESACTIVAMOS INTERRUPCIONES GLOBALES
	LDI R16, (1 << CLKPCE)//HABILITAMOS EL PRESCALADO DE EL OSCILADOR
	STS CLKPR, R16
	LDI R16, (1 << CLKPS2) //INDICAMOS EL PRESCALER 16MHz/16 = 1Mhz
	STS CLKPR, R16

	//CONFIGURACIONES PRELIMINARES DE LAS INTERRUPCIONES
	CALL TIMER1_SETUP
	CALL TIMER0_SETUP
	CALL PIN_CHANGE_SETUP
	
	//DEFININOMOS NUESTRAS SALIDAS
	// DISPLAY
	SBI DDRD, DDD0
	SBI PORTD, PORTD0
	SBI DDRD, DDD1
	CBI PORTD, PORTD1
	SBI DDRD, DDD2
	CBI PORTD, PORTD2
	SBI DDRD, DDD3
	CBI PORTD, PORTD3
	SBI DDRD, DDD4
	CBI PORTD, PORTD4
	SBI DDRD, DDD5
	CBI PORTD, PORTD5
	SBI DDRD, DDD6
	CBI PORTD, PORTD6
	SBI DDRD, DDD7
	CBI PORTD, PORTD7

	//MULTIPLEXEO
	SBI DDRB, DDB0
	SBI DDRB, DDB1
	SBI DDRB, DDB2
	SBI DDRB, DDB3
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3

	//LEDS
	SBI DDRB, DDB4
	SBI DDRB, DDB5
	SBI DDRC, DDC0
	CBI PORTB, PORTB4
	CBI PORTB, PORTB5
	CBI PORTC, PORTC0
	SBI DDRC, DDC1
	CBI PORTC, PORTC0

	//DEFINIMOS LAS SALIDAS PARA LAS INTERRUPCIONES PIN_CHANGE
	CBI DDRC, DDC2
	CBI DDRC, DDC3
	CBI DDRC, DDC4
	CBI DDRC, DDC5
	SBI PORTC, PORTC2
	SBI PORTC, PORTC3
	SBI PORTC, PORTC4
	SBI PORTC, PORTC5

	//LIMPIAMOS REGISTROS Y DESIGNAMOS VALORES
	CLR MODO
	CLR R21
	CLR R22
	CLR R1
	CLR R2
	IN R16, PINC
	ANDI R16, 0b00111100
	MOV R3, R16
	CLR R6
	CLR R7
	CLR R8
	CLR R9
	CLR R10
	CLR R12
	CLR R16
	CLR R17
	CLR R18
	CLR R19
	CLR R24
	LDI R25, 0x01
	CLR R26
	LDI R27, 0x01
	CLR R28
	CLR R29
	CLR R30
	CLR R31

	LDI R16, 2
	STS ALARMA_PRIMERO_HORA, R16
	STS ALARMA_SEGUNDO_HORA, R16
	STS ALARMA_PRIMERO_MIN, R16
	STS ALARMA_SEGUNDO_MIN, R16
	CLR R16
	STS CONTADOR_TIMER0, R16

	CLR R16
	SEI
/****************************************/
// Loop Infinito
MAIN_LOOP:
	CALL CHEQUEO_ALARMA //LLAMA A LA FUNCIÓN PARA VER SI LA ALARMA COINCIDE CON LA HORA
	PUSH R28
	LDI R28, 0x01
	CP R28, R2
	BREQ OVERFLOW_HORA //LLAMA LA FUNCION PARA INDICAR QUE YA PASO 10 MIN
	POP R28 
	CPI MODO, 2					//AQUI ESTAN LOS BRANCHES PARA TODAS LA FUNCIONES DEL RELOJ
	BREQ LLAMADO_SETUP_HORA
	CPI MODO, 3
	BREQ LLAMADO_SETUP_MIN
	CPI MODO, 4
	BREQ LLAMADO_SETUP_MES
	CPI MODO, 5
	BREQ LLAMADO_SETUP_DIA
	CPI MODO, 6
	BREQ LLAMADO_SETUP_ALARMA_HORA
	CPI MODO, 7
	BREQ LLAMADO_SETUP_ALARMA_MIN
	CALL COPIA						
	CPI MODO, 0					//SE COLOCA DESPUES DE LA FUNCION COPIA PARA QUE NO SOBRE ESCRIBA LOS VALORES EN LA CONFIGURACION
	BREQ LLAMADO_HORA
	CPI MODO, 1
	BREQ LLAMADO_FECHA
	RJMP MAIN_LOOP

OVERFLOW_HORA: //PRIMERA PARTE DEL MODO 0
	POP R28
	CALL DIES_MIN
	RJMP MAIN_LOOP

//AQUI SOLO LLAMA A LAS FUNCIONES DE LOS MODOS
LLAMADO_HORA:
	CALL HORA
	RJMP MAIN_LOOP

LLAMADO_FECHA:
	CALL FECHA
	RJMP MAIN_LOOP

LLAMADO_SETUP_HORA:
	CALL SETUP_HORA
	RJMP MAIN_LOOP

LLAMADO_SETUP_MIN:
	CALL SETUP_MIN
	RJMP MAIN_LOOP

LLAMADO_SETUP_DIA:
	CALL SETUP_DIA
	RJMP MAIN_LOOP

LLAMADO_SETUP_MES:
	CALL SETUP_MES
	RJMP MAIN_LOOP

LLAMADO_SETUP_ALARMA_HORA:
	CALL SETUP_ALARMA_HORA
	RJMP MAIN_LOOP

LLAMADO_SETUP_ALARMA_MIN:
	CALL SETUP_ALARMA_MIN
	RJMP MAIN_LOOP

/***********SUBRUTINAS************/

//EN TODO ESTE APARTADO LLAMA A LAS FUNCIONES DE MULTIPLEXEO DE LOS DISPLAYS Y COLOCO UNA FUNCIÓN DELAY PARA QUE SE NOTE CON MAYOR NITIDEZ

HORA:
	CALL HORA_HORAS1
	OUT PORTD, R11
	CALL DELAY
	CALL HORA_HORAS0
	OUT PORTD, R11
	CALL DELAY
	CALL HORA_MIN1
	OUT PORTD, R11
	CALL DELAY
	CALL HORA_MIN0
	OUT PORTD, R11
	CALL DELAY
	RET

FECHA:
	CALL FECHA_DIA1
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_DIA0
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_MES1
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_MES0
	OUT PORTD, R11
	CALL DELAY
	RET

SETUP_HORA:
	SBRC R6, 0
	CALL INCREMENTO_HORAS //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_HORAS //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R8, 0
	CALL REMPLAZO_HORAS //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	CALL SETUP_HORA1
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_HORA0
	OUT PORTD, R11
	CALL DELAY
	RET 

SETUP_MIN:
	SBRC R6, 0
	CALL INCREMENTO_MIN //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_MIN
	SBRC R8, 0
	CALL REMPLAZO_MIN
	CALL SETUP_MIN1
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_MIN0
	OUT PORTD, R11
	CALL DELAY
	RET 

SETUP_DIA:
	SBRC R6, 0
	CALL INCREMENTO_DIA //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_DIA
	SBRC R8, 0
	CALL REMPLAZO_DIA
	CALL SETUP_DIA1
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_DIA0
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_MES1
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_MES0
	OUT PORTD, R11
	CALL DELAY
	RET
	
SETUP_MES:
	SBRC R6, 0
	CALL INCREMENTO_MES //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_MES
	SBRC R8, 0
	CALL REMPLAZO_MES
	CALL SETUP_MES1
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_MES0
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_DIA1
	OUT PORTD, R11
	CALL DELAY
	CALL FECHA_DIA0
	OUT PORTD, R11
	CALL DELAY
	RET

SETUP_ALARMA_HORA:
	SBRC R6, 0
	CALL INCREMENTO_HORAS_ALARMA //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_HORAS_ALARMA
	CALL SETUP_HORA1_ALARMA
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_HORA0_ALARMA
	OUT PORTD, R11
	CALL DELAY
	RET


SETUP_ALARMA_MIN:
	SBRC R6, 0
	CALL INCREMENTO_MIN_ALARMA //AQUÍ VERIFICAMOS LA BANDERA PROVOCADA POR LOS BOTONES
	SBRC R7, 0
	CALL DECREMENTO_MIN_ALARMA
	CALL SETUP_MIN1_ALARMA
	OUT PORTD, R11
	CALL DELAY
	CALL SETUP_MIN0_ALARMA
	OUT PORTD, R11
	CALL DELAY
	RET
	
/****************CONFIGURACIONES DE LAS INTERRUPCIONES************************/
TIMER1_SETUP:
	LDI R16, 0x00
	STS TCCR1A, R16 //ACTIVAMOS LA CONFIGURACION
	LDI R16, (1 << CS12)|(1 << CS10)
	STS TCCR1B, R16 //INDICAMOS EL PRESCALADO QUE QUEREMOS (1024)
	LDI R16, HIGH(T1_VALOR)
	STS TCNT1H, R16
	LDI R16, LOW(T1_VALOR)
	STS TCNT1L, R16 //CARGAMOS EL VALOR INICIAL
	LDI R16, (1 << TOIE1)
	STS TIMSK1, R16
	RET

TIMER0_SETUP:
	LDI R16, 0x00
	OUT TCCR0A, R16	//ACTIVAMOS LA CONFIGURACION
	LDI R16, (1 << CS02)|(1 << CS00)
	OUT TCCR0B, R16	//INDICAMOS EL PRESCALADO QUE QUEREMOS (1024)
	LDI R16, 12
	OUT TCNT0, R16	//CARGAMOS EL VALOR INICIAL
	LDI R16, (1 << TOIE0)
	STS TIMSK0, R16
	RET

PIN_CHANGE_SETUP:
	LDI R16, (1 << PCIE1) //HABILITAMOS PIN CHANGE EN EL PUERTO C
	STS PCICR, R16
	LDI R16, (1 << PCINT10)|(1 << PCINT11)|(1 << PCINT12)|(1 << PCINT13) //HABILITAMOS LA INTERRUPCIÓN A LOS BITS 2, 3, 4 Y 5
	STS PCMSK1, R16
	RET

/**************FUNCIONES DEL MULTIPLEXEO Y SACAR VALORES DE LA TABLITA********************/
SETUP_HORA0_ALARMA:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, ALARMA_SEGUNDO_HORA 
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_HORA1_ALARMA:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, ALARMA_PRIMERO_HORA 
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	SBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_MIN0_ALARMA:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, ALARMA_SEGUNDO_MIN 
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	SBI PORTB, PORTB3
	RET

SETUP_MIN1_ALARMA:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, ALARMA_PRIMERO_MIN
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	SBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_MES1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_PRIMERO_MES
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	SBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_MES0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_SEGUNDO_MES
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	SBI PORTB, PORTB3
	RET

SETUP_DIA0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_SEGUNDO_DIA
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_DIA1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_PRIMERO_DIA
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	SBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_HORA1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_PRIMERO_HORA
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	SBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_HORA0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_SEGUNDO_HORA
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_MIN1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_PRIMERO_MIN
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	SBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

SETUP_MIN0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	LDS R10, COPIA_SEGUNDO_MIN
	ADD ZL, R10 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	SBI PORTB, PORTB3
	RET

FECHA_DIA1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R26 
	ADC ZH, R1 
	LPM R11, Z
	SBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

FECHA_DIA0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R25 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

FECHA_MES1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R28 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	SBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

FECHA_MES0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R27 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	SBI PORTB, PORTB3
	RET

HORA_HORAS1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R16 
	ADC ZH, R1 
	LPM R11, Z
	SBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

HORA_HORAS0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R18 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	CBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET	

HORA_MIN1:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R19 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	SBI PORTB, PORTB2
	CBI PORTB, PORTB3
	RET

HORA_MIN0:
	LDI ZH, HIGH(disp7seg<<1) 
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R24 
	ADC ZH, R1 
	LPM R11, Z
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1
	CBI PORTB, PORTB2
	SBI PORTB, PORTB3
	RET

/****************RUTINAS MODO 1******************/
DIES_MIN:
	CLR R2
	RJMP DIES_MINUTOS_2

DIES_MINUTOS_2:
	CLR R24
	INC R19
	CPI R19, 0x06 //SI LLEGA A 6 ES QUE YA HAY 60 MIN = 1 HORA
	BREQ UNA_HORA
	RET

UNA_HORA:
	CLR R19
	INC R18
	CPI R18, 0x04 //HACE LA COMPARACIÓN CON 4 PARA VERIFICAR SI YA ES UN DIA
	BREQ VERIF_DIA
	CPI R18, 0x0A
	BREQ DIES_HORA
	RET

VERIF_DIA:
	CPI R16, 2
	BREQ UN_DIA //SI YA VERIFICAMOS QUE ES 24 EN LAS HORAS, INCREMENTAMOS UN DÍA. 
	RET

DIES_HORA:
	CLR R18
	INC R16
	RET

/**************************************RUTINAS MODO 2********************************************/
UN_DIA:
	CLR R16
	CLR R18
	INC R25
	CPI R25, 1 // VERIFICAMOS TODOS LAS POSIBILIDADES EN EL CAMBIO DE UNIDADES DE DIA
	BREQ VERIF_30
	CPI R25, 2
	BREQ VERIF_31
	CPI R25, 9
	BREQ VERIF_FEB
	CPI R25, 10
	BREQ VERIF_10_DIAS
	RET

//REALIZAMOS LAS RESPECTIVAS VERIFICACIONES 
VERIF_10_DIAS:
	CLR R25
	INC R26
	RET

VERIF_30:
	CPI R26, 3
	BREQ MESES_30
	RET

MESES_30:
	CPI R27, 1
	BREQ VERIF_NOV
	CPI R27, 4
	BREQ MESES_30_CONFIRMADO
	CPI R27, 6
	BREQ MESES_30_CONFIRMADO
	CPI R27, 9
	BREQ VERIF_SEP	
	RET

VERIF_SEP:
	LDI R27, 0XFF //LE ASIGNAMOS ESE VALOR PARA QUE AL MOMENTO DE INCREMENTAR R27 LLEGE A 0
	INC R28
	RJMP MESES_30_CONFIRMADO

VERIF_NOV:
	CPI R28, 1
	BREQ MESES_30_CONFIRMADO
	RET

MESES_30_CONFIRMADO:
	LDI R25, 1 //LE ASIGNAMOS 1 PARA QUE EMPIECE DESDE PRIMERO 
	INC R27
	CLR R26
	RET

VERIF_31:
	CPI R26, 3
	BREQ MESES_31
	RET

//TODOS LOS POSIBLES MESES CON 31 DIAS
MESES_31:
	CPI R27, 0
	BREQ VERIF_OCTUBRE
	CPI R27, 1
	BREQ VERIF_ENERO
	CPI R27, 2
	BREQ VERIF_DICIEMBRE
	CPI R27, 3
	BREQ MESES_30_CONFIRMADO
	CPI R27, 5
	BREQ MESES_30_CONFIRMADO
	CPI R27, 7
	BREQ MESES_30_CONFIRMADO	
	CPI R27, 8
	BREQ MESES_30_CONFIRMADO
	RET

VERIF_ENERO:
	CPI R28, 0
	BREQ MESES_31_CONFIRMADO
	RET

VERIF_OCTUBRE:
	CPI R28, 1
	BREQ MESES_31_CONFIRMADO
	RET

VERIF_DICIEMBRE:
	CPI R28, 1
	BREQ VUELTA_AL_SOL
	RET

VERIF_FEB:
	CPI R26, 2
	BREQ VERIF_MES_FEB
	RET

//SE ASEGURO QUE YA CUMPLIO UN AÑO POR LO QUE SE INICIA TODO NUEVAMENTE
VUELTA_AL_SOL:
	LDI R25, 1
	CLR R26
	LDI R27, 1
	CLR R28
	RET

MESES_31_CONFIRMADO:
	LDI R25, 1
	INC R27
	CLR R26
	RET	

//BRANCHES PARA CADA OPCION
VERIF_MES_FEB:
	CPI R27, 2
	BREQ VERIF_FEBRERO
	RET

VERIF_FEBRERO:
	CPI R28, 0
	BREQ FEBRERO_CONFIRMADO
	RET

FEBRERO_CONFIRMADO:
	INC R27
	LDI R25, 0x01
	CLR R26
	RET

/****************************************RUTINAS MODO 3 (MINUTOS)*****************************************************************/
//AQUI ME QUEDÉ SIN REGISTROS ENTONCES EMPECÉ A USAR LAS LOCALIDADES DE LA RAM
//EN ESTE MODO ES PRACTIMANTE MUY PARECIDO AL MODO 0 SOLO QUE LO SACAMOS Y GUARDAMOS EN LA RAM
INCREMENTO_MIN:
	CLR R6
	LDS R21, COPIA_SEGUNDO_MIN
	INC R21
	CPI R21, 0x0A
	BREQ OVERFLOW_MIN_UNIDADES

	STS COPIA_SEGUNDO_MIN, R21
	RET

OVERFLOW_MIN_UNIDADES:
	CLR R21
	STS COPIA_SEGUNDO_MIN, R21

	LDS R21, COPIA_PRIMERO_MIN
	INC R21
	CPI R21, 0x06
	BREQ OVERFLOW_MIN_DECENAS

	STS COPIA_PRIMERO_MIN, R21
	RET

OVERFLOW_MIN_DECENAS:
	CLR R21
	STS COPIA_PRIMERO_MIN, R21
	RET

//ESTO ES LO UNICO DIFERNETE Y ADICIONAL DEL MODO 0
DECREMENTO_MIN:
	CLR R7
	LDS R21, COPIA_SEGUNDO_MIN
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_MIN
	STS COPIA_SEGUNDO_MIN, R21
	RET

UNDERFLOW_MIN:
	LDS R21, COPIA_PRIMERO_MIN
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_TOTAL_MIN
	STS COPIA_PRIMERO_MIN, R21

	LDI R21, 0x09
	STS COPIA_SEGUNDO_MIN, R21
	RET

UNDERFLOW_TOTAL_MIN:
	LDI R21, 0x05
	STS COPIA_PRIMERO_MIN, R21
	LDI R21, 0x09
	STS COPIA_SEGUNDO_MIN, R21
	RET

/***************************RUTINAS MODO 2 (HORAS)********************************/
//AQUI ES LA MISMA HISTORIA DEL MODO 1, SOLO QUE SACANDO Y REGRESANDO A LA RAM
INCREMENTO_HORAS:
	CLR R6
	LDS R21, COPIA_SEGUNDO_HORA
	INC R21
	CPI R21, 0x04
	BREQ VERIF_24_HORAS
	CPI R21, 0x0A
	BREQ OVERFLOW_HORAS_SETUP
	STS COPIA_SEGUNDO_HORA, R21
	RET

OVERFLOW_HORAS_SETUP:
	CLR R21
	STS COPIA_SEGUNDO_HORA, R21
	LDS R21, COPIA_PRIMERO_HORA
	INC R21
	STS COPIA_PRIMERO_HORA, R21
	RET

VERIF_24_HORAS:
	STS COPIA_SEGUNDO_HORA, R21
	LDS R21, COPIA_PRIMERO_HORA
	CPI R21, 2
	BREQ CONFIRMADO_24_HORAS
	RET

CONFIRMADO_24_HORAS:
	CLR R21
	STS	COPIA_PRIMERO_HORA, R21
	LDS R21, COPIA_SEGUNDO_HORA
	CLR R21
	STS COPIA_SEGUNDO_HORA, R21
	RET

//ESTO ES LO QUE TIENE EXTRA PERO SOLO ES IR REVISANDO LOS UNDERFLOWS
DECREMENTO_HORAS:
	CLR R7
	LDS R21, COPIA_SEGUNDO_HORA
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_HORA
	STS COPIA_SEGUNDO_HORA, R21
	RET

UNDERFLOW_HORA:
	LDS R21, COPIA_PRIMERO_HORA
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_TOTAL
	STS COPIA_PRIMERO_HORA, R21

	CPI R21, 0x02
	BREQ PONER_3_UNIDADES

	LDI R21, 0x09
	STS COPIA_SEGUNDO_HORA, R21
	RET

PONER_3_UNIDADES:
	LDI R21, 0x03
	STS COPIA_SEGUNDO_HORA, R21
	RET

UNDERFLOW_TOTAL:
	LDI R21, 0x02
	STS COPIA_PRIMERO_HORA, R21
	LDI R21, 0x03
	STS COPIA_SEGUNDO_HORA, R21
	RET

/*******************RUTINAS MODO 3 (DIAS)*********************/
INCREMENTO_DIA:
	CLR R6
	CPI R28, 0
	BRNE INC_MES_DECENA_1 //COMPRAMOS EL REGISTRO DE DECENAS DE MES PARA VER SI ES EN LOS ULTIMOS 3 MESES DEL AÑO
	CPI R27, 2 //AQUÍ YA SABEMOS QUE SON LOS PRIMEROS 9
	BREQ VERIF_TOPE_28
	CPI R27, 4
	BREQ VERIF_TOPE_30
	CPI R27, 6
	BREQ VERIF_TOPE_30
	CPI R27, 9
	BREQ VERIF_TOPE_30
	RJMP VERIF_TOPE_31

INC_MES_DECENA_1:
	CPI R27, 1//AQÍ YA SABEMOS QUE SON LOS ULTIMOS 3 MESES
	BREQ VERIF_TOPE_30      //NOVIEMBRE
	RJMP VERIF_TOPE_31      //OCTUBRE O DICIEMBRE

//VERIFICAR SI YA SE LLEGO A ESA FECHA EN FEBRERO
VERIF_TOPE_28:
	LDS R21, COPIA_PRIMERO_DIA
	CPI R21, 2
	BRNE INC_DIA_NORMAL
	LDS R21, COPIA_SEGUNDO_DIA
	CPI R21, 8
	BRNE INC_DIA_NORMAL
	RJMP REINICIO_DIA_01

//VERIFICAR SI SE LLEGO A ESA FECHA 
VERIF_TOPE_30:
	LDS R21, COPIA_PRIMERO_DIA
	CPI R21, 3
	BRNE INC_DIA_NORMAL
	LDS R21, COPIA_SEGUNDO_DIA
	CPI R21, 0
	BRNE INC_DIA_NORMAL
	RJMP REINICIO_DIA_01

VERIF_TOPE_31:
	LDS R21, COPIA_PRIMERO_DIA
	CPI R21, 3
	BRNE INC_DIA_NORMAL
	LDS R21, COPIA_SEGUNDO_DIA
	CPI R21, 1
	BRNE INC_DIA_NORMAL
	RJMP REINICIO_DIA_01

//FUNCION PARA INCREMENTAR DE FORMA NORMAL
INC_DIA_NORMAL:
	LDS R21, COPIA_SEGUNDO_DIA
	INC R21
	CPI R21, 10
	BREQ OVERFLOW_DIA_UNIDADES
	STS COPIA_SEGUNDO_DIA, R21
	RET

OVERFLOW_DIA_UNIDADES:
	CLR R21
	STS COPIA_SEGUNDO_DIA, R21
	LDS R21, COPIA_PRIMERO_DIA
	INC R21
	STS COPIA_PRIMERO_DIA, R21
	RET

//COLOCA EN INICIO DE MES
REINICIO_DIA_01:
	CLR R21
	STS COPIA_PRIMERO_DIA, R21
	LDI R21, 1
	STS COPIA_SEGUNDO_DIA, R21
	RET

DECREMENTO_DIA:
	CLR R7
	LDS R21, COPIA_PRIMERO_DIA
	CPI R21, 0
	BRNE DEC_DIA_NORMAL
	LDS R21, COPIA_SEGUNDO_DIA
	CPI R21, 1
	BRNE DEC_DIA_NORMAL
	RJMP CARGAR_MAX_DIA_MES


//DECREMENTO NORMAL
DEC_DIA_NORMAL:
	LDS R21, COPIA_SEGUNDO_DIA
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_DIA_UNIDADES
	STS COPIA_SEGUNDO_DIA, R21
	RET

UNDERFLOW_DIA_UNIDADES:
	LDS R21, COPIA_PRIMERO_DIA
	DEC R21
	STS COPIA_PRIMERO_DIA, R21
	LDI R21, 9
	STS COPIA_SEGUNDO_DIA, R21
	RET
//DETERMINAR LOS PRIMEROS NUEVE MESES
CARGAR_MAX_DIA_MES:
	CPI R28, 0
	BRNE DEC_MES_DECENA_1_
//MESES DEL 1 AL 9
	CPI R27, 2
	BREQ CARGAR_28
	CPI R27, 4
	BREQ CARGAR_30
	CPI R27, 6
	BREQ CARGAR_30
	CPI R27, 9
	BREQ CARGAR_30
	RJMP CARGAR_31

//MESES DEL 10 AL 12
DEC_MES_DECENA_1_:
	CPI R27, 1
	BREQ CARGAR_30       //NOVIEMBRE
	RJMP CARGAR_31       //OCTUBRE O DICIEMBRE

CARGAR_28:
	LDI R21, 2
	STS COPIA_PRIMERO_DIA, R21
	LDI R21, 8
	STS COPIA_SEGUNDO_DIA, R21
	RET

CARGAR_30:
	LDI R21, 3
	STS COPIA_PRIMERO_DIA, R21
	CLR R21
	STS COPIA_SEGUNDO_DIA, R21
	RET

CARGAR_31:
	LDI R21, 3
	STS COPIA_PRIMERO_DIA, R21
	LDI R21, 1
	STS COPIA_SEGUNDO_DIA, R21
	RET

/*************RUTINAS MODO 3 (MESES)***************/

INCREMENTO_MES:
	CLR R6
	LDS R21, COPIA_SEGUNDO_MES
	INC R21
	CPI R21, 10
	BREQ OVERFLOW_MES_SETUP
	CPI R21, 3
	BREQ VERIF_ANO_SETUP
	STS COPIA_SEGUNDO_MES, R21
	RET

//PARA VER SI SE CUMPLIERON LOS PRIMEROS 9 MESES
OVERFLOW_MES_SETUP:
	CLR R21
	STS COPIA_SEGUNDO_MES, R21
	LDS R21, COPIA_PRIMERO_MES
	INC R21
	STS COPIA_PRIMERO_MES, R21
	RET

//VERIFICAR SI SE CUMPIÓ UN AÑO
VERIF_ANO_SETUP:
	STS COPIA_SEGUNDO_MES, R21
	LDS R21, COPIA_PRIMERO_MES
	CPI R21, 1
	BREQ UN_ANO_SETUP
	RET

//SETUP DE INICIO DE AÑO
UN_ANO_SETUP:
	CLR R21
	STS COPIA_PRIMERO_MES, R21
	LDS R21, COPIA_SEGUNDO_MES
	LDI R21, 1
	STS COPIA_SEGUNDO_MES, R21
	RET

//MISMA IDEA SOLO QUE CON UNDERFLOWS Y DECREMENTO DEL REGISTRO 
DECREMENTO_MES:
	CLR R7
	LDS R21, COPIA_PRIMERO_MES
	CPI R21, 0
	BRNE DEC_MES_DECENA_1
	LDS R21, COPIA_SEGUNDO_MES
	CPI R21, 1
	BREQ DEC_MES_01_A_12
	DEC R21
	STS COPIA_SEGUNDO_MES, R21
	RET

//POSIBLES CASOS DEL DECREMENTO
DEC_MES_01_A_12:
	LDI R21, 1
	STS COPIA_PRIMERO_MES, R21
	LDI R21, 2
	STS COPIA_SEGUNDO_MES, R21
	RET

//DECREMENTO NORMAL
DEC_MES_DECENA_1:
	LDS R21, COPIA_SEGUNDO_MES
	CPI R21, 0
	BREQ DEC_MES_10_A_09
	DEC R21
	STS COPIA_SEGUNDO_MES, R21
	RET

DEC_MES_10_A_09:
	CLR R21
	STS COPIA_PRIMERO_MES, R21
	LDI R21, 9
	STS COPIA_SEGUNDO_MES, R21
	RET

/***********RUTINAS MODO 4 (MINUTOS)*****************/
//MISMA IDEA QUE EL INCREMENTO CON MINUTOS DEL MODO 2
INCREMENTO_MIN_ALARMA:
	CLR R6
	LDS R21, ALARMA_SEGUNDO_MIN
	INC R21
	CPI R21, 0x0A
	BREQ OVERFLOW_MIN_UNIDADES_ALARMA

	STS ALARMA_SEGUNDO_MIN, R21
	RET

//REVISAMOS OVERFLOWS EN LAS UNIDADES
OVERFLOW_MIN_UNIDADES_ALARMA:
	CLR R21
	STS ALARMA_SEGUNDO_MIN, R21

	LDS R21, ALARMA_PRIMERO_MIN
	INC R21
	CPI R21, 0x06 //SI YA SE LLEGÓ A UNA HORA
	BREQ OVERFLOW_MIN_DECENAS_ALARMA

	STS ALARMA_PRIMERO_MIN, R21
	RET

OVERFLOW_MIN_DECENAS_ALARMA:
	CLR R21
	STS ALARMA_PRIMERO_MIN, R21
	RET

//MISMA IDEA DEL DECREMENTO DE MINUTOS DEL MODO 2
DECREMENTO_MIN_ALARMA:
	CLR R7
	LDS R21, ALARMA_SEGUNDO_MIN
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_MIN_ALARMA
	STS ALARMA_SEGUNDO_MIN, R21
	RET

UNDERFLOW_MIN_ALARMA:
	LDS R21, ALARMA_PRIMERO_MIN
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_TOTAL_MIN_ALARMA
	STS ALARMA_PRIMERO_MIN, R21

	LDI R21, 0x09
	STS ALARMA_SEGUNDO_MIN, R21
	RET

//UNDERFLOW PARA PASAR DE 00 A 59
UNDERFLOW_TOTAL_MIN_ALARMA:
	LDI R21, 0x05
	STS ALARMA_PRIMERO_MIN, R21
	LDI R21, 0x09
	STS ALARMA_SEGUNDO_MIN, R21
	RET

/*************RUTINAS MODO 4 (HORAS)**************/
//MISMA IDEA PARA INCREMENTAR HORAS DEL MODO 2
//EL UNICO CAMBIO ES QUE SE COLOCA EN OTRO REGISTRO EN LA RAM
INCREMENTO_HORAS_ALARMA:
	CLR R6
	LDS R21, ALARMA_SEGUNDO_HORA
	INC R21
	CPI R21, 0x04
	BREQ VERIF_24_HORAS_ALARMA
	CPI R21, 0x0A
	BREQ OVERFLOW_HORAS_SETUP_ALARMA
	STS ALARMA_SEGUNDO_HORA, R21
	RET

OVERFLOW_HORAS_SETUP_ALARMA:
	CLR R21
	STS ALARMA_SEGUNDO_HORA, R21
	LDS R21, ALARMA_PRIMERO_HORA
	INC R21
	STS ALARMA_PRIMERO_HORA, R21
	RET

//PARA VER SI SE LLEGÓ A UN DIA COMPLETO 
VERIF_24_HORAS_ALARMA:
	STS ALARMA_SEGUNDO_HORA, R21
	LDS R21, ALARMA_PRIMERO_HORA
	CPI R21, 2
	BREQ CONFIRMADO_24_HORAS_ALARMA
	RET

CONFIRMADO_24_HORAS_ALARMA:
	CLR R21
	STS	ALARMA_PRIMERO_HORA, R21
	LDS R21, ALARMA_SEGUNDO_HORA
	CLR R21
	STS ALARMA_SEGUNDO_HORA, R21
	RET

//MISMA IDEA DEL DECREMENTO DEL MODO 2
DECREMENTO_HORAS_ALARMA:
	CLR R7
	LDS R21, ALARMA_SEGUNDO_HORA
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_HORA_ALARMA
	STS ALARMA_SEGUNDO_HORA, R21
	RET

UNDERFLOW_HORA_ALARMA:
	LDS R21, ALARMA_PRIMERO_HORA
	DEC R21
	CPI R21, 0xFF
	BREQ UNDERFLOW_TOTAL_ALARMA
	STS ALARMA_PRIMERO_HORA, R21

	CPI R21, 0x02
	BREQ PONER_3_UNIDADES_ALARMA

	LDI R21, 0x09
	STS ALARMA_SEGUNDO_HORA, R21
	RET

PONER_3_UNIDADES_ALARMA:
	LDI R21, 0x03
	STS ALARMA_SEGUNDO_HORA, R21
	RET

//CUANDO SE PASA DE 00 A 23 HORAS
UNDERFLOW_TOTAL_ALARMA:
	LDI R21, 0x02
	STS ALARMA_PRIMERO_HORA, R21
	LDI R21, 0x03
	STS ALARMA_SEGUNDO_HORA, R21
	RET

/**********RUTINAS PARA COMPARAR HORA CON ALARMA***************/
//LAS PRIMERAS 4 FUNCIONES SOLO COMPARAN LA HORA DE LOS REGISTROS DE HORA CON LA DE CONFIGURACION DE ALARMA
CHEQUEO_ALARMA:
	LDS R21, ALARMA_SEGUNDO_MIN
	CP R21, R24
	BREQ VERFI_ALARMA_DECENAS
	RJMP NO_COINCIDE

VERFI_ALARMA_DECENAS:
	LDS R21, ALARMA_PRIMERO_MIN
	CP R21, R19
	BREQ VERIF_ALARMA_HORA
	RJMP NO_COINCIDE

VERIF_ALARMA_HORA:
	LDS R21, ALARMA_SEGUNDO_HORA
	CP R21, R18
	BREQ VERIF_ALARMA_DECENAS_HORAS
	RJMP NO_COINCIDE

VERIF_ALARMA_DECENAS_HORAS:
	LDS R21, ALARMA_PRIMERO_HORA
	CP R21, R16
	BREQ SI_COINCIDE
	RJMP NO_COINCIDE
//AQUÍ ES DONDE SE INDICAN QUE ES LO QUE ESTA SUCEDIENDO, SI ES IGUAL LA HORA O NO
SI_COINCIDE:
	SBR R29, (1<<0)         //COLOCAMOS UN 1 EN EL BIT 0
	SBRC R29, 1             //SI LA CONFIRMACIÓN FUE HECHA NO SUENA LA ALARMA
	RET						//SE SALTA ESTE RET SI COINCIDE Y NO SE APACHA CONFIRMACIÓN 
	SBI PORTC, PORTC0
	RET

NO_COINCIDE:
	CBR R29, (1<<0)|(1<<1)  //SI NO COINCIDE SE SE LIMPIA LA BANDERA DE CONFIRMACIÓN PARA QUE PUEDA SONAR NUEVAMENTE DESPUÉS
	CBI PORTC, PORTC0
	RET

/************RUTINAS PARA REMPLAZAR VALORES EN MODO SETUP******************/
//AQUÍ SOLO REMPLAZAMOS LOS VALORES EN LOS REGISTROS DE LOS PRIMEROS DOS MODOS (0 Y 1)
REMPLAZO_HORAS:
	LDS R16, COPIA_PRIMERO_HORA
	LDS R18, COPIA_SEGUNDO_HORA
	CLR R6
	CLR R7
	CLR R8
	RET	

REMPLAZO_MIN:
	LDS R19, COPIA_PRIMERO_MIN
	LDS R24, COPIA_SEGUNDO_MIN
	CLR R6
	CLR R7
	CLR R8
	RET

REMPLAZO_MES:
	LDS R28, COPIA_PRIMERO_MES
	LDS R27, COPIA_SEGUNDO_MES
	CLR R6
	CLR R7
	CLR R8
	RET

REMPLAZO_DIA:
	LDS R26, COPIA_PRIMERO_DIA
	LDS R25, COPIA_SEGUNDO_DIA
	CLR R6
	CLR R7
	CLR R8
	RET

/***********************RUTINAS INDEPENDIENTES DE LOS MODOS**************************************/
//PARA QUE SE VEAN BIEN LOS DISPLAYS
DELAY:
	INC R22
	CPI R22, 255
	BRNE DELAY
	RET 
//PARA ESCRIBIR LOS VALORES DE LA HORA EN LA RAM
COPIA: 
	MOV R9, R24
	STS COPIA_SEGUNDO_MIN, R9
	MOV R9, R19
	STS COPIA_PRIMERO_MIN, R9
	MOV R9, R18
	STS COPIA_SEGUNDO_HORA, R9
	MOV R9, R16
	STS COPIA_PRIMERO_HORA, R9
	MOV R9, R27
	STS COPIA_SEGUNDO_MES, R9
	MOV R9, R28
	STS COPIA_PRIMERO_MES, R9
	MOV R9, R25
	STS COPIA_SEGUNDO_DIA, R9
	MOV R9, R26
	STS COPIA_PRIMERO_DIA, R9
	RET

/****************************************/
// Interrupt routines
TIMER1_ISR:
	PUSH R28
	LDI R28, HIGH(T1_VALOR)
	STS TCNT1H, R28
	LDI R28, LOW(T1_VALOR) //CARGAMOS EL VALOR OTRA VEZ PARA QUE SEA UN MINUTO 
	STS TCNT1L, R28
	INC R24 
	CPI R24, 0x0A //VERIFICAMOS SI LLEGÓ A 10 MIN 
	BRNE OUT_TIMER1_ISR
	INC R2 //ACTIVAMOS BANDERA DE 10 MIN
	RJMP OUT_TIMER1_ISR

OUT_TIMER1_ISR:
	POP R28
	RETI

/*********************************/
TIMER0_ISR:
	PUSH R21
	LDI R21, 12
	OUT TCNT0, R16	//CARGAMOS EL VALOR INICIAL
	LDS R21, CONTADOR_TIMER0
	INC R21
	CPI R21, 2 //CUANDO LLEGUE A 2 SERÍA 0.5 MS
	BREQ CONTINUACION_TIMER0
	STS CONTADOR_TIMER0, R21
	RJMP OUT_TIMER0_ISR

CONTINUACION_TIMER0:
	SBI PINC, PINC1 //AQUÍ HACE QUE PARPADEEN LOS LEDS DEL DISPLAY
	CLR R21
	STS CONTADOR_TIMER0, R21
	//VERIFICA EL MODO PARA LA SECUENCIA DE LOS LEDS
	CPI MODO, 0
	BREQ LED_MODO_0
	CPI MODO, 1
	BREQ LED_MODO_1
	CPI MODO, 2
	BREQ LED_MODO_2_3
	CPI MODO, 3
	BREQ LED_MODO_2_3
	CPI MODO, 4
	BREQ LED_MODO_4_5
	CPI MODO, 5
	BREQ LED_MODO_4_5
	CPI MODO, 6
	BREQ LED_MODO_6_7
	CPI MODO, 7
	BREQ LED_MODO_6_7
	RJMP OUT_TIMER0_ISR

LED_MODO_0:
	SBI PORTB, PORTB4
	CBI PORTB, PORTB5
	RJMP OUT_TIMER0_ISR

LED_MODO_1:
	CBI PORTB, PORTB4
	SBI PORTB, PORTB5
	RJMP OUT_TIMER0_ISR

LED_MODO_2_3:
	CBI PORTB, PORTB5
	SBI PINB, PINB4 //TOGGLE PARA INDICAR MODO SETUP
	RJMP OUT_TIMER0_ISR

LED_MODO_4_5:
	SBI PINB, PINB5 //TOGGLE PARA INDICAR MODO SETUP
	CBI PORTB, PORTB4
	RJMP OUT_TIMER0_ISR

LED_MODO_6_7:
	SBI PINB, PINB5 //TOGGLE PARA INDICAR MODO SETUP
	SBI PINB, PINB4 
	RJMP OUT_TIMER0_ISR

OUT_TIMER0_ISR:
	POP R21
	RETI
/************************/
 PIN_CHANGE_ISR:
	PUSH R27
	IN R27, PINC
	ANDI R27, 0b00111100
	MOV R5, R27
	EOR R5, R3 //PARA VER QUE PINES CAMBIARON DE VALOR
	SBRS R5, 5 //PARA VER SI CAMBIÓ EL DE CONFIRMACIÓN 
	RJMP REVISAR_MODO
	SBRC R27, 5
	RJMP REVISAR_MODO
	SBRS R29, 0 //SALTA LA SIGUENTE LINEA SI NO SE A PRESIONADO EL BOTON CONFIRMACIÓN 
	RJMP REVISAR_MODO
	SBR R29, (1<<1) //ACTIVA LA FLAG PARA EL "SILENCIADO"
	CBI PORTC, PORTC0
	INC R8 //ACTIVA LA FLAG DEL BOTON
	RJMP OUT_PIN_CHANGE_ISR

REVISAR_MODO:
	SBRS R5, 2 //AQUÍ VA REVISANDO MODO POR MODO PARA VER EN DONDE FUE EL CAMBIO
	RJMP OTRO_MODO
	SBRC R27, 2
	RJMP OUT_PIN_CHANGE_ISR
	INC MODO
	CPI MODO, 8
	BREQ OVERFLOW_MODOS //OVERFLOW PARA LOS MODOS
	RJMP OUT_PIN_CHANGE_ISR

OVERFLOW_MODOS:
	CLR MODO
	RJMP OUT_PIN_CHANGE_ISR

OTRO_MODO: //OTRO MODO APARTE DE LOS PRIMEROS 2
	MOV R3, R27
	CPI MODO, 0
	BREQ OUT_PIN_CHANGE_ISR
	CPI MODO, 1
	BREQ OUT_PIN_CHANGE_ISR
	RJMP SUBIR

SUBIR: //VERIFICAR SI HUBO CAMBIO EN LOS BOTONES DE SUBIDA O BAJADA
	SBRS R5, 3
	RJMP BAJAR
	SBRS R27, 3
	RJMP OUT_PIN_CHANGE_ISR
	INC R6 //ACTIVA FLAG DE SUBIDA
	RJMP OUT_PIN_CHANGE_ISR

BAJAR: 
	SBRS R5, 4
	RJMP CONFIRMACION
	SBRS R27, 4
	RJMP OUT_PIN_CHANGE_ISR
	INC R7 //ACTIVA LA FLAG DE BAJADA
	RJMP OUT_PIN_CHANGE_ISR

CONFIRMACION:
	SBRS R5, 5
	RJMP OUT_PIN_CHANGE_ISR
	SBRS R27, 5
	RJMP OUT_PIN_CHANGE_ISR
	INC R8 //ACTIVA FLAG DE CONFIRMACION 
	RJMP OUT_PIN_CHANGE_ISR

OUT_PIN_CHANGE_ISR:
	MOV R3, R27
	POP R27
	RETI
/****************************************/
//TABLA DE VALORES PARA EL DISPLAY 
disp7seg:
	.db 0x81, 0xCF, 0x92, 0x86, 0xCC, 0xA4, 0xA0, 0x8F, 0x80, 0x84, 0x88, 0xE0, 0xB1, 0xC2, 0xB0, 0xB8